### ISSUE TITLE
Aggiornamento norme di progetto

### ISSUE THREAD

**Issue by 4ourSquared** [4ourSquared/LumosMinima#5]
Aggiornamento norme di progetto per aggiunta di utilizzo di GitHub Projects e GitHub Issues

**Comment by nicolasalberti00** [comment]
Creato il branch apposito, come descritto nelle Norme di Progetto appena aggiornate. Richiedo la verifica della pull request, se è tutto ok si possono anche cancellare i commenti alla sezione 4.1, che è stata oggetto di modifica.
